[package]
name = "liftinstall"
version = "0.1.0"
authors = ["James <jselby@jselby.net>"]
repository = "https://github.com/j-selby/liftinstall.git"
documentation = "https://liftinstall.jselby.net"
description = "An adaptable installer for your application."
build = "build.rs"

[dependencies]
web-view = {git = "https://github.com/j-selby/web-view.git", rev = "752106e4637356cbdb39a0bf1113ea3ae8a14243"}

hyper = "0.11.27"
futures = "0.1.25"
mime_guess = "1.8.6"
url = "1.7.2"

reqwest = "0.9.12"
number_prefix = "0.3.0"

serde = "1.0.89"
serde_derive = "1.0.89"
serde_json = "1.0.39"

toml = "0.5.0"

semver = {version = "0.9.0", features = ["serde"]}
regex = "1.1.5"

dirs = "1.0.5"
zip = "0.5.1"
xz2 = "0.1.6"
tar = "0.4"

log = "0.4"
fern = "0.5"
chrono = "0.4.6"

clap = "2.32.0"

[build-dependencies]
walkdir = "2.2.7"
serde = "1.0.89"
serde_derive = "1.0.89"
toml = "0.5.0"
which = "2.0.1"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["psapi", "winbase", "winioctl", "winnt"] }
widestring = "0.4.0"

[target.'cfg(not(windows))'.dependencies]
sysinfo = "0.8.2"
slug = "0.1.4"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"
cc = "1.0"
